name: WP Auto Update S&P500

on:
  schedule:
    # UTC 21:30 = 日本時間 06:30 (火-土)
    - cron: '30 21 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        env:
          # ここで1つにまとめたSecretsを渡す
          WP_CREDENTIALS: ${{ secrets.WP_CREDENTIALS }}
        run: python update_wp.py
